import Vue from "vue"
import Vuex from "vuex"

Vue.use(Vuex)

const state = {
	users:{
		admin:{
			password:'123456',
			authority:0
		},
		user:{
			password:'123456',
			authority:1
		}
	},
	categories:[
		[
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'cdd',
				username:'admin',
				role:'管理员',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			}
		],
		[
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			},
			{
				name:'ljx',
				username:'user',
				role:'用户',
				apartment:'调度部门',
				method:'部门数控',
				time:'不限',
				phone:''
			}
		],
	]
}
const store = new Vuex.Store({
	state,
})

export default store